### PR TITLE
Iced 0.13 squash

### PR DESCRIPTION
**Pull request by wash2**
This is up to date with upstream master, and refactors the sctk shell to be integrated into the winit shell. It's been tested with cosmic-settings, examples from libcosmic, cosmic-applets, and cosmic-launcher. It seems to be in a good state to me, but we may need to make small adjustments as we update some more apps.

### CODE REVIEW

**Comment by ryanabx** [comment]
\*totally definitely 100% reads through all 53000 lines of code\* uhh LGTM?

In realness I'll test some things on my own application, but congratulations! This is a big deal 😎

**Comment by ryanabx** [comment]
Two things to start

the `sctk_todos` example fails to run immediately with the `scrollable content must not fill its vertical scrolling axis` thing:

[sctk_todos.log](https://github.com/user-attachments/files/17424828/sctk_todos.log)


I can't compile my iced application due to winit not having `SuggestedBounds`. Is this gated behind a feature I'm not using?

Compilation error:

```
   Compiling iced_winit v0.14.0-dev (https://github.com/pop-os/iced?branch=iced-0.13-squash#956dc807)
error[E0599]: no variant or associated item named `SuggestedBounds` found for enum `winit::event::WindowEvent` in the current scope
   --> /home/ryanbrue/.cargo/git/checkouts/iced-14fbad96f5d3e3c7/956dc80/winit/src/conversion.rs:309:22
    |
309 |         WindowEvent::SuggestedBounds(bounds) => {
    |                      ^^^^^^^^^^^^^^^ variant or associated item not found in `WindowEvent`

For more information about this error, try `rustc --explain E0599`.
error: could not compile `iced_winit` (lib) due to 1 previous error
```

My feature list:

`iced = { git = "https://github.com/pop-os/iced", branch = "iced-0.13-squash", features = [ "wayland", "winit", "tiny-skia", "wgpu", "image", "svg", "fira-sans", "auto-detect-theme", "async-std" ] }`

**Comment by wash2** [comment]
> Two things to start
> 
> the `sctk_todos` example fails to run immediately with the `scrollable content must not fill its vertical scrolling axis` thing:
> 
> [sctk_todos.log](https://github.com/user-attachments/files/17424828/sctk_todos.log)
> 
> I can't compile my iced application due to winit not having `SuggestedBounds`. Is this gated behind a feature I'm not using?
> 
> Compilation error:
> 
> ```
>    Compiling iced_winit v0.14.0-dev (https://github.com/pop-os/iced?branch=iced-0.13-squash#956dc807)
> error[E0599]: no variant or associated item named `SuggestedBounds` found for enum `winit::event::WindowEvent` in the current scope
>    --> /home/ryanbrue/.cargo/git/checkouts/iced-14fbad96f5d3e3c7/956dc80/winit/src/conversion.rs:309:22
>     |
> 309 |         WindowEvent::SuggestedBounds(bounds) => {
>     |                      ^^^^^^^^^^^^^^^ variant or associated item not found in `WindowEvent`
> 
> For more information about this error, try `rustc --explain E0599`.
> error: could not compile `iced_winit` (lib) due to 1 previous error
> ```
> 
> My feature list:
> 
> `iced = { git = "https://github.com/pop-os/iced", branch = "iced-0.13-squash", features = [ "wayland", "winit", "tiny-skia", "wgpu", "image", "svg", "fira-sans", "auto-detect-theme", "async-std" ] }`

Weird, sctk_todos runs fine on my machine. Ill double check that there is no Fill in a scrollable though. For the suggested bounds issue, maybe a cargo update would help?

**Review by mmstick — APPROVED** [review]
We should make a branch based on the current version of the master branch before force-pushing this.

**Comment by wash2** [comment]
> We should make a branch based on the current version of the master branch before force-pushing this.

Ok I'll make a branch and a tag for the current version

**Comment by ryanabx** [comment]
> Weird, sctk_todos runs fine on my machine. Ill double check that there is no Fill in a scrollable though. For the suggested bounds issue, maybe a cargo update would help?

I'll give it a try after work today!

**Comment by wash2** [comment]
https://github.com/pop-os/iced/tree/libcosmic-iced-0.12 & https://github.com/pop-os/iced/releases/tag/libcosmic-v0.12

**Pull request merged**
