### PR TITLE
Cosmic advanced text

### PR DESCRIPTION
**Pull request by wash2**
This adds changes for accessibility and the sctk shell to the latest from upstream.

### CODE REVIEW

**Comment by ids1024** [comment]
We'll want to archive the existing version before this is pushed to master. Perhaps a tag like `0.6.0-cosmic`?

**Comment by wash2** [comment]
> We'll want to archive the existing version before this is pushed to master. Perhaps a tag like `0.6.0-cosmic`?

Ya, that sounds good. I'll do that now.

**Comment by wash2** [comment]
Ahh a lazy widget seems to be panicking during layout in the launcher.

**Comment by ids1024** [comment]
Seems to be working okay updating things to use this (https://github.com/pop-os/cosmic-osd/pull/2, https://github.com/pop-os/cosmic-workspaces-epoch/pull/1, https://github.com/pop-os/cosmic-settings/pull/37).

Looking at cosmic-settings, font size is noticably larger. Not sure if that's an issue or if the sizing is more correct now, but things will need adjustment either way.

The `todos_sctk` example crashes on adding a task with `thread 'main' panicked at 'Wrong window id: Id(2)', examples/todos_sctk/src/main.rs:292:21`. Window sizing also doesn't seem to be right in that example when tiled; the active frame rendered by cosmic-comp doesn't match the window.

**Pull request merged**
